version: "3.7"
services:
  client:
    container_name: cbc-client-container
    build:
      context: ./client/
      dockerfile: dockerfile
    ports:
      - "80:8000"
  api:
    container_name: cbc-api-container
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_PORT: ${MYSQL_PORT}
      MYSQL_HOST: ${MYSQL_HOST}
    build:
      context: ./api/
      dockerfile: dockerfile
    ports:
      - "8001:8001"
  db:
    image: mariadb
    container_name: cbc-mariadb-container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "8002:3306"
    volumes:
      - mariadb-volume:/var/lib/mysql
volumes:
  mariadb-volume:
